<?php

use Cissee\WebtreesExt\Http\RequestHandlers\TomSelectSharedPlace;
use Fisharebest\Webtrees\Location;
use Fisharebest\Webtrees\Tree;

/**
 * @var string        $at "@" or "" (or unset).
 * @var Location|null $location
 * @var string|null   $class
 * @var string|null   $id
 * @var string        $name
 * @var Tree          $tree
 */

$at = $at ?? '';

//use a special tom-select-shared-place,
//respective script is in js/webtreesExt.phtml

?>

<select
    autocomplete="off"
    class="form-select tom-select-shared-place <?= $class ?? '' ?>"
    data-url="<?= e(route(TomSelectSharedPlace::class, ['tree' => $tree->name(), 'at' => $at])) ?>"
    id="<?= e($id ?? $name) ?>"
    name="<?= e($name) ?>"
    <?= ($disabled ?? false) ? 'disabled="disabled"' : '' ?>
    <?= ($required ?? false) ? 'required="required"' : '' ?>
>
    <?php if (($location ?? null) instanceof Location) : ?>
        <option value="<?= e($at . $location->xref() . $at) ?>">
            <?= view('selects/location', ['location' => $location]) ?>
        </option>
    <?php else : ?>
        <option value="">&nbsp;</option>
    <?php endif ?>
</select>
