<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Ramsey\Uuid\Uuid;
?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?php
    $count_individuals = [];
    $count_families = [];

    if ($showLinkCounts) {
      //note: performance isn't great in case of $useIndirectLinks - don't see a way to improve this
      //thus $showLinkCounts

      foreach ($sharedPlaces as $sharedPlace) {
        $count_individuals[$sharedPlace->xref()] = count($sharedPlace->linkedIndividuals('_LOC'));
        $count_families[$sharedPlace->xref()] = count($sharedPlace->linkedFamilies('_LOC'));
      }
    }
    ?>

    <?php
    //create new shared place
    $id = /* $fact . */ Uuid::uuid4()->toString();
    ?>

    <div class="input-group">
        <span class="input-group-btn">
            <button 
                class="btn btn-secondary" 
                type="button" 
                data-toggle="modal" 
                data-target="#wt-ajax-modal" 
                data-href="<?=
                e(route('module', [
                    'module' => $moduleName,
                    'action' => 'CreateSharedPlace',
                    'tree' => $tree->name()
                ]));
                ?>" 
                data-select-id="<?= $id ?>" 
                title="<?= I18N::translate('Create a shared place'); ?>">
                    <?= view('icons/add') ?>
            </button>
        </span>
    </div>

    <table
        class="table table-bordered table-sm wt-table-note datatables"
        <?= view('lists/datatables-attributes') ?>
        data-columns="<?=
        e(json_encode([
            null,
            ['visible' => $showLinkCounts/* array_sum($count_individuals) > 0 */],
            ['visible' => $showLinkCounts/* array_sum($count_families) > 0 */]
        ]))
        ?>"
        >
        <caption class="sr-only">
            <?= $caption ?? I18N::translate('Shared places') ?>
        </caption>

        <thead>
            <tr>
                <th><?= I18N::translate('Shared place') ?></th>
                <th><?= MoreI18N::xlate('Individuals') ?></th>
                <th><?= MoreI18N::xlate('Families') ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($sharedPlaces as $sharedPlace) : ?>
              <?php
              if (!$sharedPlace->canShow()) {
                continue;
              }
              ?>
              <tr class="<?= $sharedPlace->isPendingDeletion() ? 'wt-old' : ($sharedPlace->isPendingAddition() ? 'wt-new' : '') ?>">
                  <!-- Title -->
                  <td data-sort="<?= e($sharedPlace->fullName()) ?>">
                      <?php foreach ($sharedPlace->namesNN() as $name) : ?>
                        <a title="<?= $name ?>" href="<?= e($sharedPlace->url()) ?>" class="<?= $name == $sharedPlace->fullName() ? 'name2' : '' ?>">
                            <?= $name ?>
                        </a>
                        <br>
                      <?php endforeach ?>
                  </td>

                  <!-- Count of linked individuals --> 
                  <td class="center" data-sort="<?= $count_individuals[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_individuals[$sharedPlace->xref()] ?? 0) ?>
                  </td>

                  <!-- Count of linked families -->
                  <td class="center" data-sort="<?= $count_families[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_families[$sharedPlace->xref()] ?? 0) ?>
                  </td>
              </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>

<?= view('modals/ajax') ?>
