<?php

use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

//cf record-page-links.phtml

/**
 * @var string                      $details
 * @var ?Collection<int,Family>     $linked_families
 * @var ?Collection<int,Individual> $linked_individuals
 * 
 * //[RC] added
 * @var ?Collection<int,Location>   $llSharedPlaces
 * 
 * @var ?Collection<int,Media>      $linked_media_objects
 * @var ?Collection<int,Note>       $linked_notes
 * @var ?Collection<int,Source>     $linked_sources
 * @var Tree                        $tree
 */

?>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" data-bs-toggle="tab" role="tab" href="#details">
            <?= MoreI18N::xlate('Details') ?>
        </a>
    </li>

    <?php if ($linked_individuals instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#individuals">
                <?= MoreI18N::xlate('Individuals') ?>
                <?= view('components/badge', ['count' => $linked_individuals->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_families instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#families">
                <?= MoreI18N::xlate('Families') ?>
                <?= view('components/badge', ['count' => $linked_families->count()]) ?>
            </a>
        </li>
    <?php endif ?>
        
    <?php if ($llSharedPlaces instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#llSharedPlaces">
                <?= I18N::translate('Next lower-level shared places') ?>
                <?= view('components/badge', ['count' => $llSharedPlaces->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_media_objects instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#media">
                <?= MoreI18N::xlate('Media objects') ?>
                <?= view('components/badge', ['count' => $linked_media_objects->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_sources instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#sources">
                <?= MoreI18N::xlate('Sources') ?>
                <?= view('components/badge', ['count' => $linked_sources->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_notes instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#notes">
                <?= MoreI18N::xlate('Notes') ?>
                <?= view('components/badge', ['count' => $linked_notes->count()]) ?>
            </a>
        </li>
    <?php endif ?>
</ul>

<div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="details">
        <?= $details ?>
    </div>

    <?php if ($linked_individuals instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="individuals">
            <?= view('lists/individuals-table', ['individuals' => $linked_individuals, 'sosa' => false, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_families instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="families">
            <?= view('lists/families-table', ['families' => $linked_families, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($llSharedPlaces instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="llSharedPlaces">
            <?= view('lists/locations-table', ['locations' => $llSharedPlaces, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>
    
    <?php if ($linked_media_objects instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="media">
            <?= view('lists/media-table', ['media_objects' => $linked_media_objects, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_sources instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="sources">
            <?= view('lists/sources-table', ['sources' => $linked_sources, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_notes instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="notes">
            <?= view('lists/notes-table', ['notes' => $linked_notes, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>
</div>
