<?php

use Cissee\WebtreesExt\Module\ModuleVestalInterface;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;

//cf record-page.phtml

/**
 * @var Collection<int,Fact>|null       $clipboard_facts
 * @var Collection<int,Family>|null     $linked_families
 * @var Collection<int,Individual>|null $linked_individuals
 *
 * //[RC] added
 * @var Collection<int,Location>|null   $llSharedPlaces
 *
 * @var Collection<int,Media>|null      $linked_media_objects
 * @var Collection<int,Note>|null       $linked_notes
 * @var Collection<int,Source>|null     $linked_sources
 * @var GedcomRecord                    $record
 * @var Tree                            $tree
 *
 * @var string $hierarchyHtml
 * @var string $summaryHtml
 *
 * @var ModuleVestalInterface           $module
 *
 * //$module must also provide getHelpAction for 'Predecessor'!
 * //$module may also provide preferences for 'RESTRICTED_PLACE_HISTORY'!
 */

?>

<?= view('record-page-pending', ['record' => $record]) ?>


<div class="d-flex mb-4">
    <h2 class="wt-page-title mx-auto">
        <?= $record->fullName() ?>
    </h2>
    <?php if ($record->canEdit()) : ?>
        <?= view($moduleName . '::shared-place-page-menu', ['clipboard_facts' => $clipboard_facts, 'record' => $record]) ?>
    <?php endif ?>
</div>

<div class="wt-page-content">
    <?php if ($llSharedPlaces instanceof Collection || $linked_families instanceof Collection || $linked_individuals instanceof Collection || $linked_media_objects instanceof Collection || $linked_notes instanceof Collection || $linked_sources instanceof Collection) : ?>
        <?= view($moduleName . '::shared-place-page-links', [
            'details' => view($moduleName . '::shared-place-page-details', [
                'hierarchyHtml' => $hierarchyHtml,
                'summaryHtml' => $summaryHtml,
                'clipboard_facts' => $clipboard_facts,
                'record' => $record,
                'module' => $module,
            ]),

            'linked_families'      => $linked_families,
            'linked_individuals'   => $linked_individuals,
            'llSharedPlaces'       => $llSharedPlaces,
            'linked_media_objects' => $linked_media_objects,
            'linked_notes'         => $linked_notes,
            'linked_sources'       => $linked_sources,
            'tree'                 => $tree,

            'record'               => $record,
            'module'               => $module,
        ]) ?>
    <?php else : ?>
        <?= view($moduleName . '::shared-place-page-details', [
            'hierarchyHtml' => $hierarchyHtml,
            'summaryHtml' => $summaryHtml,
            'clipboard_facts' => $clipboard_facts,
            'record' => $record,
            'module' => $module,
            ]) ?>
    <?php endif ?>
</div>

<?php
//for help link
?>
<?= view('modals/ajax') ?>
