<?php

use Cissee\WebtreesExt\Http\RequestHandlers\CreateSharedPlaceAction;
use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;
use Ramsey\Uuid\Uuid;
use Vesta\VestaAdminController;
?>

<h2 class="wt-page-title">
    <?= $title ?>
</h2>

<div class="wt-page-content">
    <?php if ($hasLocationsToFix) : ?>
      <h3>
          <?= I18N::translate('Important note:') ?>
      </h3>
      <p>
          <?= I18N::translate('This tree has shared places with comma-separated name parts, while at the same time the option to \'Use hierarchical shared places\' is selected.') ?>
          <?= I18N::translate('This leads to inconsistencies when mapping places to shared places, and in general doesn\'t match the specification for shared places (which earlier versions of this custom module didn\'t follow strictly).') ?>
      </p>
      <p>
          <?= I18N::translate('It is recommended to run the data fix for this custom module to resolve this issue.') ?>
      </p>
    <?php endif ?>          
    <?php
    $count_individuals = [];
    $count_families = [];

    if ($showLinkCounts) {
      //note: performance isn't great in case of $useIndirectLinks - don't see a way to improve this
      //thus $showLinkCounts

      foreach ($sharedPlaces as $sharedPlace) {
        $count_individuals[$sharedPlace->xref()] = count($sharedPlace->linkedIndividuals('_LOC'));
        $count_families[$sharedPlace->xref()] = count($sharedPlace->linkedFamilies('_LOC'));
      }
    }
    ?>

    <?php
    //create new shared place
    $id = /* $fact . */ Uuid::uuid4()->toString();
    ?>

    <div class="input-group d-flex justify-content-between">
        <span class="input-group-btn">
            <button 
                class="btn btn-secondary" 
                type="button" 
                data-toggle="modal" 
                data-target="#wt-ajax-modal-vesta" 
                data-href="<?= e(route(CreateSharedPlaceAction::class, ['tree' => $tree->name()])) ?>" 
                data-select-id="<?= $id ?>" 
                title="<?= I18N::translate('Create a shared place'); ?>">
                    <?= view('icons/add') ?>
            </button>
        </span>
        <?php if ($link !== null) : ?>
          <p>
              <?= $link->format() ?>
          </p>
        <?php endif ?>
    </div>

    <table
        class="table table-bordered table-sm wt-table-note datatables"
        <?= view('lists/datatables-attributes') ?>
        data-columns="<?=
        e(json_encode([
            null,
            ['visible' => $showLinkCounts/* array_sum($count_individuals) > 0 */],
            ['visible' => $showLinkCounts/* array_sum($count_families) > 0 */]
        ]))
        ?>"
        >
        <caption class="sr-only">
            <?= $caption ?? I18N::translate('Shared places') ?>
        </caption>

        <thead>
            <tr>
                <th><?= I18N::translate('Shared place') ?></th>
                <th><?= MoreI18N::xlate('Individuals') ?></th>
                <th><?= MoreI18N::xlate('Families') ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($sharedPlaces as $sharedPlace) : ?>
              <?php
              if (!$sharedPlace->canShow()) {
                continue;
              }
              ?>
              <tr class="<?= $sharedPlace->isPendingDeletion() ? 'wt-old' : ($sharedPlace->isPendingAddition() ? 'wt-new' : '') ?>">
                  <!-- Title -->
                  <td data-sort="<?= e($sharedPlace->fullName()) ?>">
                      <?php foreach ($sharedPlace->namesNN() as $name) : ?>
                        <a title="<?= $name ?>" href="<?= e($sharedPlace->url()) ?>" class="<?= $name == $sharedPlace->fullName() ? 'name2' : '' ?>">
                            <?= $name ?>
                        </a>
                        <br>
                      <?php endforeach ?>
                  </td>

                  <!-- Count of linked individuals --> 
                  <td class="center" data-sort="<?= $count_individuals[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_individuals[$sharedPlace->xref()] ?? 0) ?>
                  </td>

                  <!-- Count of linked families -->
                  <td class="center" data-sort="<?= $count_families[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_families[$sharedPlace->xref()] ?? 0) ?>
                  </td>
              </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>

<?php
  //do not use standard modal placeholder (ajax.phtml): we may have to support specific select2 edit controls!
  //cf data-target="#wt-ajax-modal-vesta" above!

  echo view(VestaAdminController::vestaViewsNamespace() . '::modals/ajax-modal-vesta', [
                'ajax' => false,
                'select2Initializers' => $select2Initializers
    ]);
?>