<?php

use Cissee\WebtreesExt\Module\ModuleVestalInterface;
use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\Fact;
use Fisharebest\Webtrees\GedcomRecord;
use Fisharebest\Webtrees\I18N;
use Fisharebest\Webtrees\Tree;
use Illuminate\Support\Collection;
use Vesta\CommonI18N;
use Vesta\Hook\HookInterfaces\FunctionsPlaceUtils;
use Vesta\Model\FactFilter;
use Vesta\Model\PlaceStructure;
use Vesta\VestaUtils;

//cf record-page-links.phtml

/**
 * @var string                      $details
 * @var ?Collection<int,Family>     $linked_families
 * @var ?Collection<int,Individual> $linked_individuals
 * 
 * //[RC] added
 * @var ?Collection<int,Location>   $llSharedPlaces
 * 
 * @var ?Collection<int,Media>      $linked_media_objects
 * @var ?Collection<int,Note>       $linked_notes
 * @var ?Collection<int,Source>     $linked_sources
 * @var Tree                        $tree
 * 
 * @var GedcomRecord                $record
 * @var ModuleVestalInterface       $module
 * 
 * //$module must also provide getHelpAction for 'Predecessor'!
 * //$module may also provide preferences for 'RESTRICTED_PLACE_HISTORY'!
 */

$factFilter = new class($module, $record) implements FactFilter {
    
    //gah painful
    private $module;
    private $record;

    public function __construct($module, $record) {
        $this->module = $module;
        $this->record = $record;
    }
    
    //performance doesn't look great
    public function filter(Fact $fact): bool {
        $ps = PlaceStructure::fromFact($fact);
        if ($ps === null) {
            return false;
        }
        $loc = FunctionsPlaceUtils::plac2loc($this->module, $ps, false);
        if ($loc === null) {
            return false;
        }
        return ($loc->getXref() === $this->record->xref());
    }
};

?>

<ul class="nav nav-tabs" role="tablist">
    <li class="nav-item" role="presentation">
        <a class="nav-link active" data-bs-toggle="tab" role="tab" href="#details">
            <?= MoreI18N::xlate('Details') ?>
        </a>
    </li>

    <?php if ($linked_individuals instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#individuals">
                <?= MoreI18N::xlate('Individuals') ?>
                <?= view('components/badge', ['count' => $linked_individuals->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_families instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#families">
                <?= MoreI18N::xlate('Families') ?>
                <?= view('components/badge', ['count' => $linked_families->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_media_objects instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#media">
                <?= MoreI18N::xlate('Media objects') ?>
                <?= view('components/badge', ['count' => $linked_media_objects->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_sources instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#sources">
                <?= MoreI18N::xlate('Sources') ?>
                <?= view('components/badge', ['count' => $linked_sources->count()]) ?>
            </a>
        </li>
    <?php endif ?>

    <?php if ($linked_notes instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#notes">
                <?= MoreI18N::xlate('Notes') ?>
                <?= view('components/badge', ['count' => $linked_notes->count()]) ?>
            </a>
        </li>
    <?php endif ?>
        
    <?php if ($llSharedPlaces instanceof Collection) : ?>
        <li class="nav-item" role="presentation">
            <a class="nav-link" data-bs-toggle="tab" role="tab" href="#llSharedPlaces">
                <?= I18N::translate('Next lower-level shared places') ?>
                <?= view('components/badge', ['count' => $llSharedPlaces->count()]) ?>
            </a>
        </li>
    <?php endif ?>
        
    <li class="nav-item" role="presentation">
        <a class="nav-link" data-bs-toggle="tab" role="tab" href="#placeHistory">
            <?= CommonI18N::placeHistory() ?>
        </a>
    </li>
</ul>

<div class="tab-content">
    <div class="tab-pane fade show active" role="tabpanel" id="details">
        <?= $details ?>
    </div>

    <?php if ($linked_individuals instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="individuals">
            <?= view('lists/individuals-table', ['individuals' => $linked_individuals, 'sosa' => false, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_families instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="families">
            <?= view('lists/families-table', ['families' => $linked_families, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($llSharedPlaces instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="llSharedPlaces">
            <?= view('lists/locations-table', ['locations' => $llSharedPlaces, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>
    
    <?php if ($linked_media_objects instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="media">
            <?= view('lists/media-table', ['media_objects' => $linked_media_objects, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_sources instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="sources">
            <?= view('lists/sources-table', ['sources' => $linked_sources, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>

    <?php if ($linked_notes instanceof Collection) : ?>
        <div class="tab-pane fade" role="tabpanel" id="notes">
            <?= view('lists/notes-table', ['notes' => $linked_notes, 'tree' => $tree]) ?>
        </div>
    <?php endif ?>
    
    <div class="tab-pane fade" role="tabpanel" id="placeHistory">
        <?= view(VestaUtils::vestaViewsNamespace() . '::lists/place-history', [
            'individuals' => $linked_individuals, 
            'record' => $record, 
            'factFilter' => $factFilter,
            'tree' => $tree,
            'context' => 'sp',
            'module' => $module]) ?>
    </div>
</div>
