<?php

use Cissee\Webtrees\Module\PersonalFacts\DefaultAssociateFactUtils;
use Fisharebest\Webtrees\GedcomRecord;
use Vesta\VestaUtils;

/**
 * @var string                    $hierarchyHtml
 * @var string                    $summaryHtml
 * @var Collection<int,Fact>|null $clipboard_facts
 * @var GedcomRecord              $record
 * @var ModuleVestalInterface     $module
 */

?>

<table class="table wt-facts-table">
    <?php 
        echo $hierarchyHtml;
        echo $summaryHtml;
    ?>
    <?php foreach ($record->facts([], true) as $fact) : ?>
        <?php
        //we need the enhanced fact view here, e.g. for resetting GOV data
        //view('fact', ['fact' => $fact, 'record' => $record])
        ?>
        <?= view(VestaUtils::vestaViewsNamespace() . '::fact', [                    
                    'fact'                   => $fact, 
                    'record'                 => $record, 
                    'module'                 => $module,
                    'useVestals'             => false,
                    'hideCoordinates'        => false,
                    'associateFactUtils'     => new DefaultAssociateFactUtils(),
                    'styles'                 => [], //no additional styles
                    'predecessors'           => [], //not used here
                    'relToPredecessorSuffix' => '', //not used here
                    ]) ?>
    <?php endforeach ?>
</table>
