<?php

use Cissee\Webtrees\Module\SharedPlaces\SharedPlacesModule;
use Cissee\WebtreesExt\MoreI18N;
use Fisharebest\Webtrees\I18N;

$count_individuals = [];
$count_families = [];

$module = app(SharedPlacesModule::class);
$showLinkCounts = boolval($module->getPreference('LINK_COUNTS', '0'));

if ($showLinkCounts) {
  //note: performance isn't great in case of $useIndirectLinks - don't see a way to improve this
  //thus $showLinkCounts

  foreach ($locations as $sharedPlace) {
    $count_individuals[$sharedPlace->xref()] = $sharedPlace->countLinkedIndividuals('_LOC');
    $count_families[$sharedPlace->xref()] = $sharedPlace->countLinkedFamilies('_LOC');
  }
}
    
?>

<div class="wt-page-content">      
    <table
        class="table table-bordered table-sm wt-table-note datatables"
        <?= view('lists/datatables-attributes') ?>
        data-columns="<?=
        e(json_encode([
            null,
            ['visible' => true],
            ['visible' => true],
            ['visible' => true],
            ['visible' => true],
            ['visible' => true],
            ['visible' => $showLinkCounts],
            ['visible' => $showLinkCounts]
        ]))
        ?>"
        >
        <caption class="visually-hidden">
            <?= $caption ?? I18N::translate('Shared places') ?>
        </caption>

        <thead>
            <tr>
                <th><?= I18N::translate('Shared place') ?></th>
                <th><?= MoreI18N::xlate('Type') ?></th>
                <th><?= MoreI18N::xlate('Place') ?></th>
                <th><?= MoreI18N::xlate('Latitude') ?></th>
                <th><?= MoreI18N::xlate('Longitude') ?></th>
                <th><?= str_replace(' ','&nbsp;',I18N::translate('GOV id?')) ?></th>
                <th><?= MoreI18N::xlate('Individuals') ?></th>
                <th><?= MoreI18N::xlate('Families') ?></th>
            </tr>
        </thead>

        <tbody>
            <?php foreach ($locations as $sharedPlace) : ?>              
              <tr class="<?= $sharedPlace->isPendingDeletion() ? 'wt-old' : ($sharedPlace->isPendingAddition() ? 'wt-new' : '') ?>">
                  <!-- Title -->
                  <td data-sort="<?= e($sharedPlace->fullName()) ?>">
                      <?php
                        $primaryName = $sharedPlace->namesNN()[$sharedPlace->getPrimaryName()];
                      ?>
                      <a title="<?= $primaryName ?>" href="<?= e($sharedPlace->url()) ?>" class="<?= $primaryName == $sharedPlace->fullName() ? 'name2' : '' ?>">
                        <?= $primaryName ?>
                      </a>
                      <br>
                      <?php foreach ($sharedPlace->namesNN() as $name) : ?>
                        <?php
                          if ($name === $primaryName) {
                            continue;
                          }
                        ?>
                        <a title="<?= $name ?>" href="<?= e($sharedPlace->url()) ?>" class="<?= $name == $sharedPlace->fullName() ? 'name2' : '' ?>">
                            <?= $name ?>
                        </a>
                        <br>
                      <?php endforeach ?>
                  </td>
                  
                  <td data-sort="<?= e($sharedPlace->getAttribute("TYPE")) ?>">
                      <?php foreach ($sharedPlace->getAttributes("TYPE") as $type) : ?>
                        <?= $type ?>
                        <br>
                      <?php endforeach ?>
                  </td>
                  
                  <!-- Place (in hierarchy) --> 

                  <td class="center">
                      <?= $sharedPlace->primaryPlace()->shortName(true) ?>
                  </td>
                  
                  <!-- Coordinates --> 
                  <td class="center">
                      <?= $sharedPlace->printLati() ?>
                  </td>
                  <td class="center">
                      <?= $sharedPlace->printLong() ?>
                  </td>
                  
                  <!-- GOV id set? --> 
                  <td class="center">
                      <?php if ($sharedPlace->facts(['_GOV'])->isNotEmpty()) : ?>
                        <span class="wt-icon-save"><i class="fas fa-check fa-fw" aria-hidden="true"></i></span>
                        <?php endif ?>
                  </td>
                  
                  <!-- Count of linked individuals --> 
                  <td class="center" data-sort="<?= $count_individuals[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_individuals[$sharedPlace->xref()] ?? 0) ?>
                  </td>

                  <!-- Count of linked families -->
                  <td class="center" data-sort="<?= $count_families[$sharedPlace->xref()] ?? 0 ?>">
                      <?= I18N::number($count_families[$sharedPlace->xref()] ?? 0) ?>
                  </td>
              </tr>
            <?php endforeach ?>
        </tbody>
    </table>
</div>
