<?php

use Fisharebest\Webtrees\Auth;
use Vesta\Hook\HookInterfaces\GovIdEditControlsInterface;
use Vesta\Hook\HookInterfaces\GovIdEditControlsUtils;
use Vesta\VestaUtils;

//original view
echo view('::edit/edit-fact', [
            'can_edit_raw' => $can_edit_raw,
            'fact'         => $fact,
            'gedcom'       => $gedcom,
            'hidden_url'   => $hidden_url,
            'title'        => $title,
            'tree'         => $tree,
            'url'          => $url,
        ]);

//select initializers for modal placeholder ajax-modal-vesta.phtml used via CreateSharedPlaceModal, urgh
$select2Initializers = GovIdEditControlsUtils::accessibleModules($tree, Auth::user())
    ->map(function (GovIdEditControlsInterface $module) {
        return $module->govIdEditControlSelectScriptSnippet();
    })
    ->toArray();

echo view(VestaUtils::vestaViewsNamespace() . '::modals/ajax-modal-vesta', [
            'ajax' => false,
            'select2Initializers' => $select2Initializers
        ]);
?>
