<?php 
  use Fisharebest\Webtrees\I18N; 
  use Ramsey\Uuid\Uuid;
?>

<?php
  //create new shared place
  $id = /* $fact . */ Uuid::uuid4()->toString();
?>

<button 
    class="btn btn-link btn-sm" 
    type="button" 
    data-toggle="modal" 
    data-target="#wt-ajax-modal" 
    data-href="<?=
    e(route('module', [
        'module' => $moduleName,
        'action' => 'CreateSharedPlace',
        'shared-place-name' => $fact->place()->gedcomName(),
        'tree' => $fact->record()->tree()->name()
    ]));
    ?>" 
    data-select-id="<?= $id ?>" 
    title="<?= I18N::translate('Create a shared place'); ?>">
        <?= view($moduleName . '::icons/shared-place') ?>
        <span class="sr-only"><?= I18N::translate('Create a shared place') ?></span>
</button>

