<?php

use Cissee\WebtreesExt\Http\RequestHandlers\CreateSharedPlaceAction;
use Fisharebest\Webtrees\I18N;
?>

<form method="post" action="<?= e(route(CreateSharedPlaceAction::class, ['tree' => $tree->name()])) ?>" id="wt-modal-form">
    <?= csrf_field() ?>

    <?= view('modals/header', ['title' => I18N::translate('Create a shared place')]) ?>

    <div class="modal-body">
        <?= view($moduleName . '::modals/shared-place-fields', [
            'useHierarchy' => $useHierarchy,
            'sharedPlaceName' => $sharedPlaceName, 
            'selector' => $selector,
            'additionalControls' => $additionalControls,
            'requiredfacts' => $requiredfacts,
            'tree' => $tree,
            ]) ?>
    </div>

    <?= view('modals/footer-save-cancel') ?>
</form>

<?php /*View::push('javascript') no need - this is a modal!*/ ?>
<?php
  foreach ($additionalControls as $gve) {
    echo $gve->getScript();
  }
?>

<?php
//[RC] adjusted: use ajax-modal-vesta
?>
<script>
    document.getElementById('wt-modal-form').addEventListener('submit', webtrees.createRecordModalVestaSubmit);
</script>
